const { v4: uuidv4 } = require('uuid');

/**
 * Save a list of chunks to the knowledge_chunks table
 * @param {Object} params
 * @param {Object} params.supabase - Supabase client
 * @param {Array} params.chunks - Array of chunk objects with embedding data
 */
async function saveKnowledgeChunks({ supabase, chunks }) {
  // Validate input
  if (!chunks || !Array.isArray(chunks) || chunks.length === 0) {
    console.warn('⚠️ No chunks to save');
    return;
  }

  // Prepare batch insert data matching the exact database schema
  const insertData = chunks.map(chunk => ({
    id: uuidv4(),
    tenant_id: chunk.tenant_id,
    knowledge_base_id: chunk.knowledge_base_id,
    chunk_index: chunk.chunk_index,
    chunk_text: chunk.chunk_text,
    chunk_embedding: chunk.embedding
    // created_at will be auto-generated by the database
  }));

  // Batch insert for better performance
  const { data, error } = await supabase
    .from('knowledge_chunks')
    .insert(insertData);

  if (error) {
    console.error('❌ Failed to insert chunks:', error.message);
    throw error; // Re-throw to handle in calling function
  }

  console.log(`✅ Successfully inserted ${insertData.length} chunks`);
  return data;
}

module.exports = { saveKnowledgeChunks };